version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=emyrael
      - POSTGRES_DB=markt_pilot
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: python etl_script.py

volumes:
  db_data:
